@startuml

folder src {

    folder entity {

        abstract Event {
            - String name
            - Course course
            - LocalDateTime startTime
            - LocalDateTime endTime
            - Location location
            - Boolean completed

            + getName()
            + setName()
            + getCourse()
            + setCourse()
            + getStartTime()
            + setStartTime()
            + getEndTime()
            + setEndTime()
            + getDuration()
            + getLocation()
            + setLocation()
            + getCompleted()
            + setCompleted()

            + moveTime()  /' Moves start and end times in unison '/
        }

        class ClassEvent extends Event {
            - String type

            + getType()
            + setType()
        }

        class StudyEvent extends Event {
            - String[] todo

            + getTodo()
            + addTodo()
            + removeTodo()
        }

        class ReadingEvent extends Event {
            - Resource resource
            - Boolean required
            - Optional<Int[]> pages

            + getResource()
            + setResource()
            + isRequired()
            + setRequired()
            + getPages()
            + addPages()
            + removePages()
        }

        class AssignmentEvent extends Event {
            - String type
            - int percentage
            - boolean required
            - DateTime lateDueDate
            - double[] percentageReduction


            + getType()
            + setType()
            + getPercentage()
            + setPercentage()
            + isRequired()
            + setRequired()
            + getLateDueDate()
            + setLateDueDate()
            + getPercentageReduction()
            + setPercentageReduction()
        }

        class User {
            ' Unimplemented for now
        }

        class semester{
            - LocalDate startDate
            - LocalDate endDate
            - String[] courses
            - LocalDate[] holidays
            - LocalDate[] examSeason

            + LocalDate getStartDate()
            + LocalDate getEndDate()
            + String[] getCourses()
            + LocalDate[] getHolidays()
            + LocalDate[] getExamSeason()
            + void setStartDate(LocalDate date)
            + void setEndDate(LocalDate date)
            + void addHolidays(LocalDate date)
            + void addExamSeason(LocalDate date)
            + void deleteHolidays(LocalDate date)
            + void deleteExamSeason(LocalDate date)
        }

        class course {
            - ClassEvent[] classes
            - AssignmentEvent[] assignments
            - String courseContact
            - Resource[] textbooks

            + ClassEvent[] getClasses()
            + AssignmentEvent[] getAssignments()
            + String getCourseContact()
            + Resource[] getTextbooks()
            + void addClasses(ClassEvent class)
            + void deleteClasses(ClassEvent class)
            + void addAssignments(AssignmentEvent[] assignment)
            + void deleteAssignments(AssignmentEvent[] assignment)
            + void setCourseContact(String contact)
            + void addTextbooks(Resource textbooks)
            + void deleteTextbooks(Resource textbooks)
        }

        class Location{
            - String buildingName
            - String address
            - Double longitude
            - Double latitude

            + void setBuildingName(String buildingName)
            + void setAddress(String address)
            + getAddress()
            + getBuildingName()
        }

        class Resource{
            - String link
            - File bibTex

            + void setLink(String link)
            + getLink()
        }

    }  /' folder entity '/


}  /' folder src '/

@enduml