@startuml

folder src {

    folder entity {

        abstract Event {

        }

        abstract semester{
         - LocalDate startDate
         - LocalDate endDate
         - String[] courses
         - LocalDate[] holidays
         - LocalDate[] examSeason

         + getStartDate()
         + getEndDate()
         + getHolidays()
         + getExamSeason()
         + setStartDate(LocalDate date)
         + setEndDate(LocalDte date)
         + setHolidays(LocalDate[] dates)
         + setExamSeason(LocalDate[] dates)
        }

        abstract course {
        - ClassEvent[] classes
        - AssignmentEvent[] assignments
        - String courseContact
        - Resource[] textbooks

        + getClasses()
        + getAssignments()
        + getCourseContact()
        + getTextbooks()
        + setClasses(ClassEvent[] classes)
        + setAssignments(AssignmentEvent[])
        + setCourseContact(String contact)
        + setTextbooks(Resource[] textbooks)
        }

    }  /' folder entity '/

}  /' folder src '/

@enduml