@startuml

folder src {

    folder entity {

        abstract Event {
            -String name
            -Course course
            -LocalDateTime startTime
            -LocalDateTime endTime
            -Location location
            -Boolean completed

            +getName()
            +setName()
            +getCourse()
            +setCourse()
            +getStartTime()
            +setStartTime()
            +getEndTime()
            +setEndTime()
            +getDuration()
            +getLocation()
            +setLocation()
            +getCompleted()
            +setCompleted()

            +move()  /' Moves start and end times in unison '/
        }

        class ClassEvent extends Event {
        String type
        }

        class StudyEvent extends Event {
        String[] toDoList
        }

        class ReadingEvent extends Event {

        }

        class AssignmentEvent extends Event {

        }

        class User {
            ' Unimplemented for now
        }

        abstract semester{
         - LocalDate startDate
         - LocalDate endDate
         - String[] courses
         - LocalDate[] holidays
         - LocalDate[] examSeason

         + getStartDate()
         + getEndDate()
         + getStartDate()
         + getStartDate()

        }

        abstract course {
        - ClassEvent[] classes
        - AssignmentEvent[] assignments
        - String courseContact
        - Resource textbook

        }

    }  /' folder entity '/

}  /' folder src '/

@enduml